# Generated by Django 4.2.30 on 2026-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumaccess',
            name='accent_colour',
            field=models.CharField(default='green', max_length=20),
        ),
    ]
