# Generated by Django 4.2.30 on 2026-06-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_premiumaccess_accent_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumaccess',
            name='accent_colour',
            field=models.CharField(default='matcha-mist', max_length=20),
        ),
    ]
