# Generated by Django 4.2.30 on 2026-06-11 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('game_type', models.CharField(choices=[('board_game', 'Board game'), ('card_game', 'Card game'), ('tabletop_game', 'Tabletop game'), ('video_game', 'Video game')], max_length=30)),
                ('platform', models.CharField(max_length=80)),
                ('ownership_status', models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist'), ('borrowed', 'Borrowed'), ('sold', 'Sold')], default='owned', max_length=30)),
                ('format', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('subscription', 'Subscription')], default='physical', max_length=30)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('player_count', models.CharField(blank=True, max_length=40)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
