# Generated by Django 4.2.30 on 2026-06-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField()),
                ('players', models.CharField(max_length=255)),
                ('winner', models.CharField(blank=True, max_length=120)),
                ('result_summary', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='games.game')),
            ],
            options={
                'ordering': ['-date_played', '-created_at'],
            },
        ),
    ]
